apiVersion: v1                   # Specifies the API version
kind: Service                    # Specifies the type of Kubernetes resource
metadata:
  name: db-service               # Name of the service
  namespace: migration-docker-kubernetes  # Namespace where the service will be created
spec:
  selector:                      # Selector to identify the pods this service targets
    app: db                      # Pods with the label app: db will be targeted
  ports:
    - protocol: TCP              # Protocol used by the service (TCP in this case)
      port: 5432                 # Port on which the service is exposed
