apiVersion: v1            # Specifies the API version
kind: Service             # Specifies the type of Kubernetes resource
metadata:
  name: web-service       # Name of the service
  namespace: migration-docker-kubernetes  # Namespace where the service will be created
spec:
  selector:               # Selector to identify the pods this service targets
    app: web              # Pods with the label app: web will be targeted
  ports:
    - protocol: TCP       # Protocol used by the service (TCP in this case)
      port: 80            # Port on which the service is exposed
      targetPort: 5000    # Port on the pod that the traffic will be forwarded to
